# Generated by Django 4.2.11 on 2024-04-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform_alter_flan_flan_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='cutomer_name',
            new_name='customer_name',
        ),
    ]
