# Generated by Django 4.2.11 on 2024-04-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
